# This is a GitLab CI configuration to build the project as a docker image
# The file is generic enough to be dropped in a project containing a working Dockerfile
# Author: Florent CHAUVEAU <florent.chauveau@gmail.com>
# Mentioned here: https://blog.callr.tech/building-docker-images-with-gitlab-ci-best-practices/

image: docker:latest

stages:
  - build_container
  - push

before_script:
  # docker login asks for the password to be passed through stdin for security
  # we use $CI_JOB_TOKEN here which is a special token provided by GitLab
  - echo -n $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin $CI_REGISTRY || true

build_container:
  # Use this if your GitLab runner does not use socket binding
  services:
    - docker:dind
  image: docker:latest
  stage: build_container
  only:
    - master
  except:
    - tags
  script:
    # fetches the latest image (not failing if image is not found)
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    # builds the project, passing proxy variables, and vcs vars for LABEL
    # notice the cache-from, which is going to use the image we just pulled locally
    # the built image is tagged locally with the commit SHA, and then pushed to 
    # the GitLab registry
    #  --tag $CI_REGISTRY_IMAGE:buildtest
    # 
    - >
      docker build
      --pull
      --cache-from $CI_REGISTRY_IMAGE:latest
      --tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-test
      .
    - docker push $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-test


# Here, the goal is to tag the "master" branch as "latest"
Push latest:
  # Use this if your GitLab runner does not use socket binding
  services:
    - docker:dind
  stage: push
  only:
    # Only "master" should be tagged "latest"
    - master
  except:
    - tags
  script:
    # Because we have no guarantee that this job will be picked up by the same runner 
    # that built the image in the previous step, we pull it again locally
    - docker pull $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-test
    # Then we tag it "latest"
    - docker tag $CI_REGISTRY_IMAGE:${CI_COMMIT_SHA}-test $CI_REGISTRY_IMAGE:latest
    # Annnd we push it.
    - docker push $CI_REGISTRY_IMAGE:latest
